const menu = [
    {
        item: "",
        category: "Salads",
        price: 0.00,
        image: "",
        _id: "1", 
    },
    {
        item: "",
        category: "Salads",
        price: 0.00,
        image: "",
        _id: "2", 
    },
    {
        item: "",
        category: "Salads",
        price: 0.00,
        image: "",
        _id: "3", 
    },
    {
        item: "",
        category: "Salads",
        price: 0.00,
        image: "",
        _id: "4", 
    },
    {
        item: "",
        category: "Salads",
        price: 0.00,
        image: "",
        _id: "5", 
    },
    {
        item: "",
        category: "Salads",
        price: 0.00,
        image: "",
        _id: "6", 
    },
    {
        item: "",
        category: "Soups",
        price: 0.00,
        image: "",
        _id: "1", 
    },
    {
        item: "",
        category: "Soups",
        price: 0.00,
        image: "",
        _id: "2", 
    },
    {
        item: "",
        category: "Soups",
        price: 0.00,
        image: "",
        _id: "3", 
    },
    {
        item: "",
        category: "Soups",
        price: 0.00,
        image: "",
        _id: "4", 
    },
    {
        item: "",
        category: "Soups",
        price: 0.00,
        image: "",
        _id: "5", 
    },
    {
        item: "",
        category: "Soups",
        price: 0.00,
        image: "",
        _id: "6", 
    },
    {
        item: "",
        category: "Sandwiches",
        price: 0.00,
        image: "",
        _id: "1", 
    },
    {
        item: "",
        category: "Sandwiches",
        price: 0.00,
        image: "",
        _id: "2", 
    },    
    {
        item: "",
        category: "Sandwiches",
        price: 0.00,
        image: "",
        _id: "3", 
    },    
    {
        item: "",
        category: "Sandwiches",
        price: 0.00,
        image: "",
        _id: "4", 
    },    
    {
        item: "",
        category: "Sandwiches",
        price: 0.00,
        image: "",
        _id: "5", 
    },    
    {
        item: "",
        category: "Sandwiches",
        price: 0.00,
        image: "",
        _id: "6", 
    },    
    {
        item: "",
        category: "Desserts",
        price: 0.00,
        image: "",
        _id: "1", 
    },    
    {
        item: "",
        category: "Desserts",
        price: 0.00,
        image: "",
        _id: "1", 
    },    
    {
        item: "",
        category: "Desserts",
        price: 0.00,
        image: "",
        _id: "3", 
    },    
    {
        item: "",
        category: "Desserts",
        price: 0.00,
        image: "",
        _id: "4", 
    },    
    {
        item: "",
        category: "Desserts",
        price: 0.00,
        image: "",
        _id: "5", 
    },    
    {
        item: "",
        category: "Desserts",
        price: 0.00,
        image: "",
        _id: "6", 
    },    
    {
        item: "",
        category: "Drinks",
        price: 0.00,
        image: "",
        _id: "", 
    },
    {
        item: "1",
        category: "Drinks",
        price: 0.00,
        image: "",
        _id: "2", 
    },  
    {
        item: "",
        category: "Drinks",
        price: 0.00,
        image: "",
        _id: "3", 
    },  
    {
        item: "",
        category: "Drinks",
        price: 0.00,
        image: "",
        _id: "4", 
    },  
    {
        item: "",
        category: "Drinks",
        price: 0.00,
        image: "",
        _id: "5", 
    },  
    {
        item: "",
        category: "Drinks",
        price: 0.00,
        image: "",
        _id: "6", 
    },      

];

const categories = ["Salads", "Soups", "Sandwiches", "Desserts", "Drinks"]; 

const dataServices = {
    getMenu: () => {
        return menu;
    },
    getCategories: () => {
        return categories;
    },
};

export default dataServices;
